MahoganyHills_Treehouse_MapScripts::
	.byte 0


MahoganyHills_EventScript_Fossil::
# 4 "data/maps/MahoganyHills_Treehouse/scripts.pory"
	lockall
# 5 "data/maps/MahoganyHills_Treehouse/scripts.pory"
	msgbox MahoganyHills_EventScript_Fossil_Text_0
# 6 "data/maps/MahoganyHills_Treehouse/scripts.pory"
	releaseall
	return


MahoganyHills_EventScript_Fossil_Text_0:
# 5 "data/maps/MahoganyHills_Treehouse/scripts.pory"
	.string "It's a fossil of an ancient Pokémon$"
