GranitePeak_Dojo1_MapScripts::
	.byte 0


GranitePeak_Dojo1_Expert::
# 4 "data/maps/GranitePeak_Dojo1/scripts.pory"
	lockall
# 5 "data/maps/GranitePeak_Dojo1/scripts.pory"
	faceplayer
# 6 "data/maps/GranitePeak_Dojo1/scripts.pory"
	msgbox GranitePeak_Dojo1_Expert_Text_0
# 7 "data/maps/GranitePeak_Dojo1/scripts.pory"
	msgbox GranitePeak_Dojo1_Expert_Text_1
# 8 "data/maps/GranitePeak_Dojo1/scripts.pory"
	releaseall
	return


GranitePeak_Dojo1_Expert_Text_0:
# 6 "data/maps/GranitePeak_Dojo1/scripts.pory"
	.string "Welcome to my Dojo$"

GranitePeak_Dojo1_Expert_Text_1:
# 7 "data/maps/GranitePeak_Dojo1/scripts.pory"
	.string "COMING SOON$"
