SeafloorCavern_Room2_MapScripts::
	.byte 0


GranitePeakDojoComingSoon::
# 8 "data/maps/SeafloorCavern_Room2/scripts.pory"
	lockall
# 9 "data/maps/SeafloorCavern_Room2/scripts.pory"
	faceplayer
# 10 "data/maps/SeafloorCavern_Room2/scripts.pory"
	msgbox GranitePeakDojoComingSoon_Text_0
# 11 "data/maps/SeafloorCavern_Room2/scripts.pory"
	releaseall
	return


GranitePeakDojoComingSoon_Text_0:
# 10 "data/maps/SeafloorCavern_Room2/scripts.pory"
	.string "This will be where the dojos will be\n"
	.string "hidden for you to find, coming soon!$"
