RivalsHouse_1F_MapScripts::
	.byte 0


RivalsHouse_EventScript_ItemBall::
# 6 "data/maps/RivalsHouse_1F/scripts.pory"
	lockall
# 7 "data/maps/RivalsHouse_1F/scripts.pory"
	msgbox RivalsHouse_EventScript_ItemBall_Text_0
# 8 "data/maps/RivalsHouse_1F/scripts.pory"
	releaseall
	return


RivalsHouse_EventScript_ItemBall_Text_0:
# 7 "data/maps/RivalsHouse_1F/scripts.pory"
	.string "It's a ball with a note on it:\l"
	.string "Here is your own Pokemon little bro. I'm\l"
	.string "sure you will use it to join me at\l"
	.string "becoming a champion one day when you\l"
	.string "are older.\l"
	.string "-Cassius$"
