EmderDunes_Larger_MapScripts::
	.byte 0


Edtd::
# 4 "data/maps/EmderDunes_Larger/scripts.pory"
	lockall
# 5 "data/maps/EmderDunes_Larger/scripts.pory"
	msgbox Edtd_Text_0
# 6 "data/maps/EmderDunes_Larger/scripts.pory"
	msgbox Edtd_Text_1
# 7 "data/maps/EmderDunes_Larger/scripts.pory"
	releaseall
	return


Edtd_Text_0:
# 5 "data/maps/EmderDunes_Larger/scripts.pory"
	.string "This will be a larger expanse of the\n"
	.string "desert to explore!$"

Edtd_Text_1:
# 6 "data/maps/EmderDunes_Larger/scripts.pory"
	.string "Rare Pokémon, hidden bases and large\n"
	.string "ruins to explore and find$"
