ClayHaven_House2_MapScripts::
	.byte 0


Town2_House2_Woman::
# 4 "data/maps/ClayHaven_House2/scripts.pory"
	lockall
# 5 "data/maps/ClayHaven_House2/scripts.pory"
	faceplayer
# 6 "data/maps/ClayHaven_House2/scripts.pory"
	msgbox Town2_House2_Woman_Text_0
# 7 "data/maps/ClayHaven_House2/scripts.pory"
	msgbox Town2_House2_Woman_Text_1
# 8 "data/maps/ClayHaven_House2/scripts.pory"
	releaseall
	return


Town2_House2_Man::
# 12 "data/maps/ClayHaven_House2/scripts.pory"
	lockall
# 13 "data/maps/ClayHaven_House2/scripts.pory"
	faceplayer
# 14 "data/maps/ClayHaven_House2/scripts.pory"
	msgbox Town2_House2_Man_Text_0
# 15 "data/maps/ClayHaven_House2/scripts.pory"
	releaseall
	return


Town2_House2_TV::
# 19 "data/maps/ClayHaven_House2/scripts.pory"
	lockall
# 20 "data/maps/ClayHaven_House2/scripts.pory"
	msgbox Town2_House2_TV_Text_0
# 21 "data/maps/ClayHaven_House2/scripts.pory"
	releaseall
	return


Town2_House2_Sink::
# 25 "data/maps/ClayHaven_House2/scripts.pory"
	lockall
# 26 "data/maps/ClayHaven_House2/scripts.pory"
	msgbox Town2_House2_Sink_Text_0
# 27 "data/maps/ClayHaven_House2/scripts.pory"
	releaseall
	return


Town2_House2_Woman_Text_0:
# 6 "data/maps/ClayHaven_House2/scripts.pory"
	.string "This town was founded thousand of\n"
	.string "years ago after some explorers found a\l"
	.string "strange plate in the mountains.$"

Town2_House2_Woman_Text_1:
# 7 "data/maps/ClayHaven_House2/scripts.pory"
	.string "It was the reason why lots of rare\n"
	.string "Pokémon used to be found in these\l"
	.string "mountains but it's since been stolen.$"

Town2_House2_Man_Text_0:
# 14 "data/maps/ClayHaven_House2/scripts.pory"
	.string "I heard that someone in this town can\n"
	.string "turn berries into juice.$"

Town2_House2_TV_Text_0:
# 20 "data/maps/ClayHaven_House2/scripts.pory"
	.string "It's a show about the History of Triver.\n"
	.string "It talks about how the 3 main islands\l"
	.string "where created as gifts to ancient\l"
	.string "Pokémon$"

Town2_House2_Sink_Text_0:
# 26 "data/maps/ClayHaven_House2/scripts.pory"
	.string "I wouldn't sink so low as to look in here$"
