BreakwaterPort_House4_MapScripts::
	.byte 0

BreakwaterPort_House4_EventScript_Man1::
	msgbox BreakwaterPort_House4_Text_MysteriesAtBottomOfSea, MSGBOX_NPC
	end

BreakwaterPort_House4_EventScript_Man2::
	msgbox BreakwaterPort_House4_Text_UnderwaterTrenchMossdeepSootopolis, MSGBOX_NPC
	end

BreakwaterPort_House4_Text_MysteriesAtBottomOfSea:
	.string "This planet's biggest mysteries are\n"
	.string "at the bottom of the sea.\p"
	.string "Somebody said that, but I don't know…$"

BreakwaterPort_House4_Text_UnderwaterTrenchMossdeepSootopolis:
	.string "There's a deep underwater trench\n"
	.string "between MOSSDEEP and SOOTOPOLIS.\p"
	.string "That's what someone told me, anyway.$"

