MahoganyHillsCave_WoChien_MapScripts::
	.byte 0


MahoganyHillsCave_WoChien::
# 4 "data/maps/MahoganyHillsCave_WoChien/scripts.pory"
	lockall
# 5 "data/maps/MahoganyHillsCave_WoChien/scripts.pory"
	msgbox MahoganyHillsCave_WoChien_Text_0
# 6 "data/maps/MahoganyHillsCave_WoChien/scripts.pory"
	releaseall
	return


MahoganyHillsCave_WoChien_Text_0:
# 5 "data/maps/MahoganyHillsCave_WoChien/scripts.pory"
	.string "WO CHIEN? COMING SOON$"
