SandyShoreCity_MapScripts::
	.byte 0


HauntedMansion_Sign::
# 4 "data/maps/SandyShoreCity/scripts.pory"
	lockall
# 5 "data/maps/SandyShoreCity/scripts.pory"
	msgbox HauntedMansion_Sign_Text_0
# 6 "data/maps/SandyShoreCity/scripts.pory"
	releaseall
	return


HauntedMansion_Sign_Text_0:
# 5 "data/maps/SandyShoreCity/scripts.pory"
	.string "This area is unfinished, you can explore\n"
	.string "and catch some ghost Pokémon for now\l"
	.string "though$"
