GranitePeak_House3_MapScripts::
	.byte 0


GranitePeak_House3_Script_Little_Girl::
# 5 "data/maps/GranitePeak_House3/scripts.pory"
	lock
# 6 "data/maps/GranitePeak_House3/scripts.pory"
	faceplayer
# 7 "data/maps/GranitePeak_House3/scripts.pory"
	msgbox GranitePeak_House3_Script_Little_Girl_Text_0
# 8 "data/maps/GranitePeak_House3/scripts.pory"
	release
	return


GranitePeak_House3_Script_Mother::
# 12 "data/maps/GranitePeak_House3/scripts.pory"
	lock
# 13 "data/maps/GranitePeak_House3/scripts.pory"
	faceplayer
# 14 "data/maps/GranitePeak_House3/scripts.pory"
	msgbox GranitePeak_House3_Script_Mother_Text_0
# 15 "data/maps/GranitePeak_House3/scripts.pory"
	release
	return


GranitePeak_House3_Script_Little_Girl_Text_0:
# 7 "data/maps/GranitePeak_House3/scripts.pory"
	.string "I'm so fast I'm like a Pikachu!$"

GranitePeak_House3_Script_Mother_Text_0:
# 14 "data/maps/GranitePeak_House3/scripts.pory"
	.string "My little girl always has so much energy\n"
	.string "to burn$"
