MahogonyHills_ResearchStation_MapScripts::
	.byte 0


MahoganyHills_EventScript_Fossil::
# 5 "data/maps/MahogonyHills_ResearchStation/scripts.pory"
	lockall
# 6 "data/maps/MahogonyHills_ResearchStation/scripts.pory"
	msgbox MahoganyHills_EventScript_Fossil_Text_0
# 7 "data/maps/MahogonyHills_ResearchStation/scripts.pory"
	releaseall
	return


MahoganyHills_EventScript_Fossil_Text_0:
# 6 "data/maps/MahogonyHills_ResearchStation/scripts.pory"
	.string "It's a fossil of an ancient Pokémon$"
