VerdanturfTown_WandasHouse_MapScripts::
	return


VerdanturfTown_WandasHouse_EventScript_Wally::
	lockall
	faceplayer
	msgbox VerdanturfTown_WandasHouse_EventScript_Wally_Text_0
	msgbox VerdanturfTown_WandasHouse_EventScript_Wally_Text_1
	releaseall
	return


VerdanturfTown_WandasHouse_EventScript_Wally_Text_0:
	.string "I moved here from Hoenn to take on a\n"
	.string "new challenge!$"

VerdanturfTown_WandasHouse_EventScript_Wally_Text_1:
	.string "Come back in a future update for more$"
