Jenovas_Hidden_Base_MapScripts::
	.byte 0


Jenovas_Hidden_Base_EventScript_Jenova::
# 5 "data/maps/Jenovas_Hidden_Base/scripts.pory"
	lockall
# 6 "data/maps/Jenovas_Hidden_Base/scripts.pory"
	faceplayer
# 7 "data/maps/Jenovas_Hidden_Base/scripts.pory"
	msgbox Jenovas_Hidden_Base_EventScript_Jenova_Text_0
# 8 "data/maps/Jenovas_Hidden_Base/scripts.pory"
	releaseall
	return


Jenovas_Hidden_Base_EventScript_Jenova_Text_0:
# 7 "data/maps/Jenovas_Hidden_Base/scripts.pory"
	.string "Hi I'm Jenova my secret base is coming\n"
	.string "soon.$"
