ObsidianThicketGym_MapScripts::
	.byte 0


ObsidianThicket_GymGauntlet_BugTrainer::
	trainerbattle_single BUGTRAINER_MARK, BugTrainer_Mark_Intro, BugTrainer_Mark_Outro
	msgbox Bugtrainer_Mark_PostBattle, MSGBOX_AUTOCLOSE
	end


ObsidianThicket_GymGauntlet_Gentleman::
	trainerbattle_single GENTLEMAN_ARTHUR, GentlemanArthur_Intro, GentlemanArthur_Outro
	msgbox GentlemanArthur_PostBattle, MSGBOX_AUTOCLOSE
	end


ObsidianThicket_GymGauntlet_Lass::
	trainerbattle_single LASS_JESSICA, Lass_Jessica_Intro, Lass_Jessica_Outro
	msgbox Lass_Jessica_PostBattle, MSGBOX_AUTOCLOSE
	end


ObsidianThicket_Expert_Herbert::
	trainerbattle_single EXPERT_HERBERT, Expert_Herbert_Intro, Expert_Herbert_Outro
	msgbox Expert_Herbert_PostBattle, MSGBOX_AUTOCLOSE
	end


ObsidianThicket_Matron_Angela::
	trainerbattle_single MATRON_ANGELA, Matron_Angela_Intro, Matron_Angela_Outro
	msgbox Matron_Angela_PostBattle, MSGBOX_AUTOCLOSE
	end


BugTrainer_Mark_Intro::
	.string "TODO$"

BugTrainer_Mark_Outro::
	.string "TODO$"

Bugtrainer_Mark_PostBattle::
	.string "TODO$"

GentlemanArthur_Intro::
	.string "TODO$"

GentlemanArthur_Outro::
	.string "TODO$"

GentlemanArthur_PostBattle::
	.string "TODO$"

Lass_Jessica_Intro::
	.string "TODO$"

Lass_Jessica_Outro::
	.string "TODO$"

Lass_Jessica_PostBattle::
	.string "TODO$"

Expert_Herbert_Intro::
	.string "TODO$"

Expert_Herbert_Outro::
	.string "TODO$"

Expert_Herbert_PostBattle::
	.string "TODO$"

Matron_Angela_Intro::
	.string "TODO$"

Matron_Angela_Outro::
	.string "TODO$"

Matron_Angela_PostBattle::
	.string "TODO$"
