LilycoveCity_House4_MapScripts::
	.byte 0


LilycoveCity_House4_EventScript_Man2::
# 6 "data/maps/LilycoveCity_House4/scripts.pory"
	lockall
# 7 "data/maps/LilycoveCity_House4/scripts.pory"
	faceplayer
# 8 "data/maps/LilycoveCity_House4/scripts.pory"
	msgbox LilycoveCity_House4_EventScript_Man2_Text_0
# 9 "data/maps/LilycoveCity_House4/scripts.pory"
	releaseall
	return


LilycoveCity_House4_EventScript_Man1::
# 14 "data/maps/LilycoveCity_House4/scripts.pory"
	lockall
# 15 "data/maps/LilycoveCity_House4/scripts.pory"
	faceplayer
# 16 "data/maps/LilycoveCity_House4/scripts.pory"
	msgbox LilycoveCity_House4_EventScript_Man1_Text_0
# 17 "data/maps/LilycoveCity_House4/scripts.pory"
	releaseall
	return


LilycoveCity_House4_EventScript_Man2_Text_0:
# 8 "data/maps/LilycoveCity_House4/scripts.pory"
	.string "Triver is known for it's 3 large islands\n"
	.string "but there is hundreds of smaller ones\l"
	.string "full of rare Pokémon. It's why lots of\l"
	.string "people came here thousands of years\l"
	.string "ago.$"

LilycoveCity_House4_EventScript_Man1_Text_0:
# 16 "data/maps/LilycoveCity_House4/scripts.pory"
	.string "I was once a trainer but I retired not\n"
	.string "long after the set up the Mega Mansion.\l"
	.string "So many strong trainers started coming\l"
	.string "from all over the world I couldn't keep\l"
	.string "up!$"
